kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  namespace: default
  labels:
    app: inizio
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        app: inizio
        service: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        imagePullPolicy: IfNotPresent
        args:
          - "--requirepass inizio"
        ports:
          - name: http
            containerPort: 6379
            protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: default
  labels:
    app: inizio
    service: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    service: redis
