version: '3.4'

name: inizio-application
services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge

  banking-api:
    image: ${DOCKER_REGISTRY-}banking-api
    build:
      context: .
      dockerfile: FundTransfers.BankingService.API/Dockerfile
    healthcheck:
      test: curl --fail http://localhost/healthz || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      - dapr-placement
      - sql-server
      - kafka

  banking-api-dapr:
    image: daprio/daprd:edge
    depends_on:
      - banking-api
    restart: on-failure
    network_mode: "service:banking-api"
        
  dapr-placement:
    image: daprio/dapr:edge
        
  redis:
    image: redis:alpine

  zookeeper:
      image: confluentinc/cp-zookeeper:latest

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
