apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-store
  namespace: {{ .Values.namespace }}
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
    - name: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dapr-secret-reader
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
