apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: {{ .Values.namespace }}
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "{{ .Values.dapr.redisHost }}:{{ .Values.dapr.redisPort }}"
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
  - name: keyPrefix
    value: none
